services:
  motorway-db:
    container_name: motorway-db
    build:
      context: ./docker-compose/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway
    ports:
      - 5432:5432
    networks:
      - motorway-network

  instance1: &instance
    build:
      context: .
      dockerfile: Dockerfile
    hostname: instance1
    environment:
      DB_URL: "postgres://user:password@motorway-db:5432/motorway"
      DB_POOL: 40
      PINO_LOG_LEVEL: "info"
      LOG_STREAM: "http://motorway-seq:5341"
      REDIS_URL: "redis://redis:6379"
      REQ_TIMEOUT: "2000"
      NODE_ENV: docker
      NODE_PORT: 8080
      CLUSTER: "true"
      CLUSTER_WORKERS: 5
      JWT_SECRET: pass123
      ADM_USER: user1
      PASS_USER: pass123
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'
    networks:
      - motorway-network

  instance2:
    <<: *instance
    hostname: instance2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - instance1
      - instance2
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
    networks:
      - motorway-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'
    networks:
      - motorway-network

  seq:
    image: datalust/seq:latest
    container_name: motorway-seq
    ports:
        - "5341:80"
    environment:
        - ACCEPT_EULA=Y
    networks:
      - motorway-network

networks:
  motorway-network:
    name: motorway-network
